use rand::prelude::*;
use rand_distr::{
    Distribution,
    Exp,
    LogNormal,
    Poisson,
};

#[derive(Debug, Clone, PartialEq)]
pub enum Side {
    Buy,
    Sell,
}

#[derive(Debug, Clone)]
pub struct TakerFill {
    pub taker_id: usize,
    pub side: Side,
    pub size: u64,
    pub timestamp_ms: u64,
}

/// Controls how a taker's activity "bursts". A burst is a short window of
/// elevated λ, followed by quiet. This is the key to realistic CLOB flow.
#[derive(Clone)]
pub struct BurstProfile {
    /// Base arrival rate (orders/slot) during quiet periods
    pub lambda_quiet: f64,
    /// Arrival rate during an active burst
    pub lambda_burst: f64,
    /// Probability of entering a burst in any given quiet slot
    pub burst_entry_prob: f64,
    /// Probability of exiting the burst each slot (controls burst duration)
    pub burst_exit_prob: f64,
}

impl BurstProfile {
    /// A passive, slow taker: rare, small pokes.
    pub fn passive() -> Self {
        Self {
            lambda_quiet: 0.2,
            lambda_burst: 2.5,
            burst_entry_prob: 0.05,
            burst_exit_prob: 0.4,
        }
    }

    /// A normal retail taker: occasional bursts.
    pub fn retail() -> Self {
        Self {
            lambda_quiet: 0.5,
            lambda_burst: 5.0,
            burst_entry_prob: 0.1,
            burst_exit_prob: 0.3,
        }
    }

    /// An aggressive taker: frequent, intense bursts.
    pub fn aggressive() -> Self {
        Self {
            lambda_quiet: 1.0,
            lambda_burst: 12.0,
            burst_entry_prob: 0.2,
            burst_exit_prob: 0.2,
        }
    }
}

// ── Per-taker state ────────────────────────────────────────────────────────

pub struct Taker {
    pub id: usize,
    pub burst_profile: BurstProfile,
    /// The median order size in atoms. A developer-friendly representation of `mu`.
    pub median_size: u64,
    /// The spread multiplier for order sizes, based around the [Taker::median_size].
    /// A value of 2 here would mean that order sizes range roughly from median/2 to median*2.
    /// A developer-friendly representation of `sigma`.
    pub spread_multiplier: f64,
    /// Probability this taker's next order is a buy.
    pub buy_bias: f64,
    /// Bias drifts: after a buy burst, lean sell (mean reversion behaviour).
    pub bias_reversion: f64,

    /// `mu` parameter for the underlying normal distribution.
    /// This is just the natural logarithm of [Taker::median_size].
    size_mu: f64,
    /// `sigma` parameter for the underlying normal distribution.
    /// This is just the natural logarithm of [Taker::spread_multiplier].
    size_sigma: f64,

    in_burst: bool,
    rng: StdRng,
}

impl Taker {
    pub fn new(
        id: usize,
        profile: BurstProfile,
        median_size: u64,
        spread_multiplier: f64,
        buy_bias: f64,
        seed: u64,
    ) -> Self {
        Self {
            id,
            burst_profile: profile,
            median_size,
            spread_multiplier,
            buy_bias,
            bias_reversion: 0.05,
            size_mu: (median_size as f64).ln(),
            size_sigma: spread_multiplier.ln(),
            in_burst: false,
            rng: StdRng::seed_from_u64(seed),
        }
    }

    /// Convenience constructors for demo variety
    pub fn retail(id: usize, seed: u64) -> Self {
        Self::new(id, BurstProfile::retail(), 3000, 2.0, 0.5, seed)
    }

    pub fn whale(id: usize, seed: u64) -> Self {
        // Large sizes, fat tail (high sigma), directional bias
        Self::new(id, BurstProfile::aggressive(), 15000, 4.0, 0.6, seed)
    }

    pub fn sniper(id: usize, seed: u64) -> Self {
        // Rare but precise: quiet most of the time, sudden sharp bursts
        Self::new(id, BurstProfile::passive(), 3000, 2.0, 0.5, seed)
    }

    /// Simulate one time slot. Returns fills generated by this taker.
    pub fn step(&mut self, slot_start_ms: u64, slot_duration_ms: u64) -> Vec<TakerFill> {
        let bp = &self.burst_profile;

        // Burst state machine
        self.in_burst = if self.in_burst {
            !self.rng.random_bool(bp.burst_exit_prob)
        } else {
            self.rng.random_bool(bp.burst_entry_prob)
        };

        let lambda = if self.in_burst {
            bp.lambda_burst
        } else {
            bp.lambda_quiet
        };

        // Poisson distribution is a discrete probability distribution, so it always outputs
        // an integer type, but the authors of the `rust_random` crate decided to defer
        // truncation to the user. `as u64` used below is the expected and suggested solution.
        // See here: https://rust-random.github.io/book/guide-dist.html#integers
        let n_orders = Poisson::new(lambda).unwrap().sample(&mut self.rng) as u64;

        if n_orders == 0 {
            return vec![];
        }

        let size_dist = LogNormal::new(self.size_mu, self.size_sigma).unwrap();

        // Scatter fills within the slot using an exponential inter-arrival process
        let inter_arrival = Exp::new(lambda / slot_duration_ms as f64).unwrap();
        let mut t = slot_start_ms;

        (0..n_orders)
            .map(|_| {
                let side = if self.rng.random_bool(self.buy_bias) {
                    Side::Buy
                } else {
                    Side::Sell
                };

                // Nudge bias toward 0.5 after each order (slight mean reversion)
                self.buy_bias += self.bias_reversion * (0.5 - self.buy_bias);

                let size = size_dist.sample(&mut self.rng).max(1.0) as u64;

                // Stochastic inter-arrival within the slot
                let gap = inter_arrival.sample(&mut self.rng) as u64;
                t = (t + gap).min(slot_start_ms + slot_duration_ms - 1);

                TakerFill {
                    taker_id: self.id,
                    side,
                    size,
                    timestamp_ms: t,
                }
            })
            .collect()
    }
}

pub struct Simulation {
    pub takers: Vec<Taker>,
    pub slot_duration_ms: u64,
}

impl Simulation {
    pub fn new(takers: Vec<Taker>, slot_duration_ms: u64) -> Self {
        Self {
            takers,
            slot_duration_ms,
        }
    }

    /// Run for `n_slots`, returns all fills sorted by timestamp (as a CLOB would see them)
    pub fn run(&mut self, n_slots: usize) -> Vec<TakerFill> {
        let mut all_fills: Vec<TakerFill> = (0..n_slots)
            .flat_map(|slot| {
                let t0 = slot as u64 * self.slot_duration_ms;
                self.takers
                    .iter_mut()
                    .flat_map(|taker| taker.step(t0, self.slot_duration_ms))
                    .collect::<Vec<_>>()
            })
            .collect();

        all_fills.sort_by_key(|f| f.timestamp_ms);
        all_fills
    }
}

#[test]
fn poisson_taker_example() {
    let takers = vec![
        Taker::retail(0, 42),
        Taker::retail(1, 137),
        Taker::whale(2, 9001),
        Taker::sniper(3, 31337),
        Taker::retail(4, 555),
    ];

    let mut sim = Simulation::new(takers, 200); // 200ms slots
    let fills = sim.run(50); // 50 slots = 10 seconds

    println!("{:<6} {:<10} {:<6} {:<10}", "time", "taker", "side", "size",);
    println!("{}", "-".repeat(50));

    for f in &fills {
        let bar = match f.side {
            Side::Buy => format!("\x1b[32m{:>6} BUY \x1b[0m", "▲"),
            Side::Sell => format!("\x1b[31m{:>6} SELL\x1b[0m", "▼"),
        };
        println!(
            "{}ms  taker{}  {}  {:.4}",
            f.timestamp_ms, f.taker_id, bar, f.size
        );
    }

    // Summary stats per taker
    println!("\n── Per-taker summary ──────────────────────────────");
    for id in 0..5 {
        let mine: Vec<_> = fills.iter().filter(|f| f.taker_id == id).collect();
        let buys = mine.iter().filter(|f| f.side == Side::Buy).count();
        let vol: u64 = mine.iter().map(|f| f.size).sum();
        println!(
            "Taker {}: {:>3} fills | {:>3}B / {:>3}S | vol {}",
            id,
            mine.len(),
            buys,
            mine.len() - buys,
            vol
        );
    }
    println!("Total fills: {}", fills.len());
}
