packages:
  - frontend
  - ts-sdk

catalog:
  '@biomejs/biome': 2.4.10
  '@jest/globals': ^29.7.0
  '@solana/addresses': ^6.7.0
  '@solana/kit': ^6.7.0
  '@solana/rpc-types': ^6.7.0
  '@types/node': ^24
  decimal.js: ^10.6.0
  jest: ^29.7.0
  ts-jest: ^29.4.6
  typescript: ^5.9

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
