[package]
name = "instruction-macros-traits"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
solana-address = { workspace = true, features = ["copy"] }
solana-program-error.workspace = true
serde = { version = "1.0.0", default-features = false, features = ["derive", "alloc"], optional = true }

[features]
default = []
codama = ["dep:serde"]
